version: '3.7'

services:
    api:
        environment:
            - HOST=0.0.0.0
            - PORT=3000
            - DB_FILENAME=/home/node/app/db/fasteignavaktin.db
        build:
            context: ./api
            dockerfile: dockerfile
            target: base
        restart: always
        volumes:
            - ./db:/home/node/app/db
            - ./api/src:/home/node/app/src
            - ./api/nodemon.json:/home/node/app/nodemon.json
            - ./.env:/home/node/app/.env
        ports:
            - "8080:3000"
        command: npm run dev
    realestate-fetcher:
        environment:
            - DB_FILENAME=/home/node/app/db/fasteignavaktin.db
        build:
            context: ./realestatefetcher
            dockerfile: dockerfile
        restart: always
        volumes:
            -  ./db:/home/node/app/db
            - ./.env:/home/node/app/.env
        command: /home/node/app/start.sh
    fasteignavaktin:
        build:
            context: ./fasteignavaktin
            dockerfile: dockerfile
            target: base
        restart: always
        volumes:
            - ./fasteignavaktin/src:/app/src
        ports:
            - "8000:5173"
        command: npm run dev
        depends_on:
            - api
    
      

